package Ryanpack;

import javax.swing.JOptionPane;

public class EditFlight extends javax.swing.JFrame {
    
    Main func = new Main();
    Admin admin = new Admin();
    
    public int rowIndex;
    public String flightID;
    public String pilotID;
    
    
    public EditFlight() {
        initComponents();
        
        // add padding to text fields
        func.addPaddingToJTextField(fromFld);
        func.addPaddingToJTextField(toFld);
        func.addPaddingToJTextField(departureDateFld);
        func.addPaddingToJTextField(departureTimeFld);
        func.addPaddingToJTextField(arrivalDateFld);
        func.addPaddingToJTextField(arrivalTimeFld);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editinstructionsLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromLbl = new javax.swing.JLabel();
        fromFld = new javax.swing.JTextField();
        toLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toFld = new javax.swing.JTextField();
        departureLbl = new javax.swing.JLabel();
        departureFormatLbl = new javax.swing.JLabel();
        departureDateFld = new javax.swing.JTextField();
        arrivalLbl = new javax.swing.JLabel();
        arrivalDateFld = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        departureTimeFld = new javax.swing.JTextField();
        departureFormatLbl1 = new javax.swing.JLabel();
        departureLbl1 = new javax.swing.JLabel();
        arrivalTimeFld = new javax.swing.JTextField();
        arrivalLbl1 = new javax.swing.JLabel();
        departureFormatLbl2 = new javax.swing.JLabel();
        departureFormatLbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Flight Record");
        setResizable(false);

        editinstructionsLbl.setText("Please enter the new flight details:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("Example: City, Country");

        fromLbl.setText("From:");

        fromFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromFldFocusGained(evt);
            }
        });
        fromFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFldActionPerformed(evt);
            }
        });

        toLbl.setText("To:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.gray);
        jLabel3.setText("Example: City, Country");

        toFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                toFldFocusGained(evt);
            }
        });
        toFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFldActionPerformed(evt);
            }
        });

        departureLbl.setText("Departure Date:");

        departureFormatLbl.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        departureFormatLbl.setForeground(java.awt.Color.gray);
        departureFormatLbl.setText("HH:MM");

        departureDateFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                departureDateFldFocusGained(evt);
            }
        });
        departureDateFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDateFldActionPerformed(evt);
            }
        });

        arrivalLbl.setText("Arrival Date:");

        arrivalDateFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                arrivalDateFldFocusGained(evt);
            }
        });
        arrivalDateFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalDateFldActionPerformed(evt);
            }
        });

        editBtn.setText("Edit Flight");
        editBtn.setFocusable(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        departureTimeFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                departureTimeFldFocusGained(evt);
            }
        });
        departureTimeFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeFldActionPerformed(evt);
            }
        });

        departureFormatLbl1.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        departureFormatLbl1.setForeground(java.awt.Color.gray);
        departureFormatLbl1.setText("DD/MM/YYYY");

        departureLbl1.setText("Departure Time:");

        arrivalTimeFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                arrivalTimeFldFocusGained(evt);
            }
        });
        arrivalTimeFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalTimeFldActionPerformed(evt);
            }
        });

        arrivalLbl1.setText("Arrival Time:");

        departureFormatLbl2.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        departureFormatLbl2.setForeground(java.awt.Color.gray);
        departureFormatLbl2.setText("HH:MM");

        departureFormatLbl3.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        departureFormatLbl3.setForeground(java.awt.Color.gray);
        departureFormatLbl3.setText("DD/MM/YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromFld)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toFld)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editinstructionsLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departureDateFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(departureLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(departureFormatLbl1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(arrivalDateFld, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(departureTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(departureLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(departureFormatLbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(departureFormatLbl2))
                                    .addComponent(arrivalTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arrivalLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(departureFormatLbl3)
                        .addGap(18, 18, 18)
                        .addComponent(arrivalLbl1)
                        .addGap(104, 104, 104)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editinstructionsLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLbl)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLbl)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLbl)
                    .addComponent(departureFormatLbl)
                    .addComponent(departureFormatLbl1)
                    .addComponent(departureLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalLbl)
                    .addComponent(arrivalLbl1)
                    .addComponent(departureFormatLbl2)
                    .addComponent(departureFormatLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivalDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if(fromFld.getText().isEmpty() || toFld.getText().isEmpty() || departureDateFld.getText().isEmpty() || departureTimeFld.getText().isEmpty() || arrivalDateFld.getText().isEmpty() || arrivalTimeFld.getText().isEmpty() || !departureDateFld.getText().contains("/") || !departureTimeFld.getText().contains(":") || !arrivalDateFld.getText().contains("/") || !arrivalTimeFld.getText().contains(":")){
            JOptionPane.showMessageDialog(null, "It seems one or more fields are either missing or filled incorrectly.\nPlease try again.", "Missing or Incorrect Field(s)", JOptionPane.ERROR_MESSAGE);
        }else{    
            admin.table.setValueAt(flightID, rowIndex, 0);
            admin.table.setValueAt(pilotID, rowIndex, 1);
            admin.table.setValueAt(fromFld.getText(), rowIndex, 2);
            admin.table.setValueAt(toFld.getText(), rowIndex, 3);
            admin.table.setValueAt(departureDateFld.getText() + " " + departureTimeFld.getText(), rowIndex, 4);
            admin.table.setValueAt(arrivalDateFld.getText() + " " + arrivalTimeFld.getText(), rowIndex, 5);
            admin.table.setValueAt(func.calculateFlightDuration(departureDateFld.getText() + " " + departureTimeFld.getText(), arrivalDateFld.getText() + " " + arrivalTimeFld.getText()), rowIndex, 6);
            func.saveData(admin.filePath, admin.table);
            this.dispose();
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void toFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_toFldFocusGained
        toFld.selectAll();
    }//GEN-LAST:event_toFldFocusGained

    private void fromFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromFldFocusGained
        fromFld.selectAll();
    }//GEN-LAST:event_fromFldFocusGained

    private void departureDateFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departureDateFldFocusGained
        departureDateFld.selectAll();
    }//GEN-LAST:event_departureDateFldFocusGained

    private void departureTimeFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departureTimeFldFocusGained
        departureTimeFld.selectAll();
    }//GEN-LAST:event_departureTimeFldFocusGained

    private void arrivalDateFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arrivalDateFldFocusGained
        arrivalDateFld.selectAll();
    }//GEN-LAST:event_arrivalDateFldFocusGained

    private void arrivalTimeFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arrivalTimeFldFocusGained
        arrivalTimeFld.selectAll();
    }//GEN-LAST:event_arrivalTimeFldFocusGained

    private void arrivalTimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalTimeFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_arrivalTimeFldActionPerformed

    private void fromFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_fromFldActionPerformed

    private void toFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_toFldActionPerformed

    private void departureDateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDateFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_departureDateFldActionPerformed

    private void departureTimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_departureTimeFldActionPerformed

    private void arrivalDateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalDateFldActionPerformed
        editBtnActionPerformed(evt);
    }//GEN-LAST:event_arrivalDateFldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField arrivalDateFld;
    private javax.swing.JLabel arrivalLbl;
    private javax.swing.JLabel arrivalLbl1;
    public javax.swing.JTextField arrivalTimeFld;
    public javax.swing.JTextField departureDateFld;
    private javax.swing.JLabel departureFormatLbl;
    private javax.swing.JLabel departureFormatLbl1;
    private javax.swing.JLabel departureFormatLbl2;
    private javax.swing.JLabel departureFormatLbl3;
    private javax.swing.JLabel departureLbl;
    private javax.swing.JLabel departureLbl1;
    public javax.swing.JTextField departureTimeFld;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editinstructionsLbl;
    public javax.swing.JTextField fromFld;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField toFld;
    private javax.swing.JLabel toLbl;
    // End of variables declaration//GEN-END:variables
}