package Ryanpack;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {
    
    Admin adminUI = new Admin();
    
    //@reference https://www.youtube.com/watch?v=2nk4rZgqdu0
    public Home() {
        initComponents();
        
        adminUI.addPaddingToJTextField(searchFld);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();
        searchFld = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        adminLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ryanair - Welcome");
        setResizable(false);

        welcomeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcomeLbl.setText("Welcome to the Ryanair flight utility! ");

        instructionsLbl.setText("Please enter your flight ID:");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        adminLbl.setForeground(java.awt.Color.blue);
        adminLbl.setText("Click here to access admin tools");
        adminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminLblMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLblMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFld)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adminLbl))
                    .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(instructionsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(instructionsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchFld, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(adminLbl)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            Scanner file = new Scanner(new File("data.txt"));
            
            while(file.hasNextLine()){
                String line = file.nextLine();
                
                if(line.contains(searchFld.getText())){
                    
                    String[] flightInfo = line.split("//");
                    
                    String[] flightInfoTemplate = {
                        "Flight ID: ",
                        "Pilot ID: ",
                        "From: ",
                        "To: ",
                        "Departure Time: ",
                        "Arrival Time: ",
                        "Duration (hours): "
                    };
                    
                    StringBuilder output = new StringBuilder();
                    
                    for(int i = 0; i < flightInfo.length; i++){
                        output.append(flightInfoTemplate[i] + "\n" + flightInfo[i] + "\n\n");
                        
                    }
                    
                    JOptionPane.showMessageDialog(null, output);
                    break;
                    
                }else{
                    if(!file.hasNextLine()){
                        JOptionPane.showMessageDialog(null, "Sorry, the flight ID you entered does not exist.");
                        break;
                    }
                }
            }
            
            file.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void adminLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseEntered
        Font font = adminLbl.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        adminLbl.setFont(font.deriveFont(attributes));
        adminLbl.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_adminLblMouseEntered

    private void adminLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseExited
        Font font = adminLbl.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        adminLbl.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_adminLblMouseExited

    private void adminLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseReleased
        this.dispose();
        adminUI.setVisible(true);
    }//GEN-LAST:event_adminLblMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLbl;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchFld;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}