/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ryanpack;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

public class Home extends javax.swing.JFrame {
    
    Admin adminPanel = new Admin();
    
    //@reference https://www.youtube.com/watch?v=2nk4rZgqdu0
    public Home() {
        initComponents();
        
        adminPanel.addPaddingToJTextField(userIdFld);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();
        userIdFld = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        adminLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ryanair - Welcome");
        setResizable(false);

        welcomeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcomeLbl.setText("Welcome to the Ryanair flight utility! ");

        instructionsLbl.setText("Please enter your flight ID:");

        userIdFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdFldActionPerformed(evt);
            }
        });

        backBtn.setText("Search");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        adminLbl.setForeground(java.awt.Color.blue);
        adminLbl.setText("Click here to access admin tools");
        adminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminLblMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLblMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIdFld)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instructionsLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adminLbl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(instructionsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdFld, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(adminLbl)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userIdFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void adminLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseEntered
        Font font = adminLbl.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        adminLbl.setFont(font.deriveFont(attributes));
        adminLbl.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_adminLblMouseEntered

    private void adminLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseExited
        Font font = adminLbl.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        adminLbl.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_adminLblMouseExited

    private void adminLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLblMouseReleased
        this.dispose();
        adminPanel.setVisible(true);
    }//GEN-LAST:event_adminLblMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JTextField userIdFld;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}